<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jflex</string>
		<string>flex</string>
	</array>
	<key>name</key>
	<string>JFlex</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\G</string>
			<key>end</key>
			<string>(?=^%%)</string>
			<key>name</key>
			<string>meta.package.jflex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.package.java</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.package.java</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.java</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(package)\b(?:\s*([^ ;$]+)\s*(;)?)?</string>
					<key>name</key>
					<string>meta.package.java</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(import static)\b\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.import.static.java</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.import.java</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.import.java</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.java</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>storage.modifier.import.java</string>
					<key>end</key>
					<string>\s*(?:$|(;))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.java</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.import.java</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\.</string>
							<key>name</key>
							<string>punctuation.separator.java</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\s</string>
							<key>name</key>
							<string>invalid.illegal.character_not_allowed_here.java</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(import)\b\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.import.java</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.import.java</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.import.java</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.java</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>storage.modifier.import.java</string>
					<key>end</key>
					<string>\s*(?:$|(;))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.java</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.import.java</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\.</string>
							<key>name</key>
							<string>punctuation.separator.java</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\s</string>
							<key>name</key>
							<string>invalid.illegal.character_not_allowed_here.java</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>source.java#code</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^%%</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.heading.jflex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^%%</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.heading.jflex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.macros.jflex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^%unicode(\s+[1-9][0-9]*(\.[0-9]+){0,2})?</string>
					<key>name</key>
					<string>keyword.other.jflex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^%buffer\s+[1-9][0-9]*</string>
					<key>name</key>
					<string>keyword.other.jflex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^%(eofclose|inputstreamctor)(\s+(true|false))?</string>
					<key>name</key>
					<string>keyword.other.jflex</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.jflex</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.jflex</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(%(?:class|extends|type|ctorarg|implements|include|initthrow|eofthrow|yylexthrow|throws|scanerror))\s+(.+)</string>
					<key>name</key>
					<string>meta.somearg.jflex</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.jflex</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.jflex</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(%function)\s+(\w+)</string>
					<key>name</key>
					<string>meta.funarg.jflex</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.jflex</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.jflex</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(%cupsym)\s+(\w+(\.w+)*)</string>
					<key>name</key>
					<string>meta.cupsym.jflex</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^%state</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.jflex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.states.jflex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\w+</string>
							<key>name</key>
							<string>storage.modifier.jflex</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.jflex</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\s+</string>
							<key>name</key>
							<string>meta.whitespace.jflex</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.java#comments</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\S</string>
							<key>name</key>
							<string>invalid.illegal.characater.jflex</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>^%(char|line|column|byaccj|cup2|cup(debug)?|integer|int(wrap)?|yyeof|notunix|7bit|full|8bit|16bit|caseless|ignorecase|public|apiprivate|final|abstract|debug|standalone|pack)</string>
					<key>name</key>
					<string>keyword.other.jflex</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^%(|init|initthrow|eof|eofthrow|yylexthrow|eofval){</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.jflex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^%(|init|initthrow|eof|eofthrow|yylexthrow|eofval)}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.jflex</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.classcode.jflex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.java#code</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\w+)\s*(=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.jflex</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.jflex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=^%|\w+\s*=)</string>
					<key>name</key>
					<string>meta.macro.jflex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#regexp</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>^%\S*</string>
					<key>name</key>
					<string>invalid.illegal.directive.jflex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.java#comments</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string></string>
			<key>contentName</key>
			<string>meta.rules.jflex</string>
			<key>end</key>
			<string>\z</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rules</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>charclass</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\[:(jletter|jletterdigit|letter|uppercase|lowercase|digit):\]</string>
					<key>name</key>
					<string>keyword.operator.jflex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\(d|D|s|S|w|W|p{[^}]*}|P{[^}]*})</string>
					<key>name</key>
					<string>keyword.operator.jflex</string>
				</dict>
			</array>
		</dict>
		<key>class</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.jflex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.jflex</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.class.jflex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#classcontent</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>classcontent</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\^|\-|\&amp;\&amp;|\|\|</string>
					<key>name</key>
					<string>keyword.operator.jflex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#charclass</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>match</key>
					<string>({)(\w+)(})</string>
					<key>name</key>
					<string>variable.other.macro.jflex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class</string>
				</dict>
			</array>
		</dict>
		<key>escape</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(b|n|t|f|r|R)</string>
					<key>name</key>
					<string>keyword.operator.jflex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.jflex</string>
				</dict>
			</array>
		</dict>
		<key>macro</key>
		<dict>
			<key>match</key>
			<string>({)(\s*\w+\s*)(})</string>
			<key>name</key>
			<string>variable.other.macro.jflex</string>
		</dict>
		<key>numeric</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\x[0-9a-fA-F]{2}</string>
					<key>name</key>
					<string>constant.numeric.jflex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[0-3]?[0-7]{1,2}</string>
					<key>name</key>
					<string>constant.numeric.jflex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\u[0-9a-fA-F]{6}</string>
					<key>name</key>
					<string>constant.numeric.jflex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\u[0-9a-fA-F]{4}</string>
					<key>name</key>
					<string>constant.numeric.jflex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\u{[0-9a-fA-F]{1,6}}</string>
					<key>name</key>
					<string>constant.numeric.jflex</string>
				</dict>
			</array>
		</dict>
		<key>regexp</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#repeat</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#macro</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#charclass</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.java#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.|\+|\*|\(|\)|\?|\||~|!|\$|\^|\\R|/</string>
					<key>name</key>
					<string>keyword.operator.jflex</string>
				</dict>
			</array>
		</dict>
		<key>repeat</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>{\s*\d+\s*(\s*,\s*\d+\s*)?}</string>
					<key>name</key>
					<string>keyword.operator.jflex</string>
				</dict>
			</array>
		</dict>
		<key>rules</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\&lt;\s*\w+\s*(?:,\s*\w+\s*)*\&gt;)\s*({)(?!\s*\w+\s*})</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.jflex</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.jflex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.jflex</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.states.jflex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#rules</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\&lt;\s*\w+\s*(,\s*\w+\s*)*\&gt;</string>
					<key>name</key>
					<string>variable.parameter.jflex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regexp</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;&lt;EOF&gt;&gt;</string>
					<key>name</key>
					<string>constant.language.jflex</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>({)(?!\s*\w+\s*})</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.jflex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.jflex</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.code.jflex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.java#code</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#numeric</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.jflex</string>
	<key>uuid</key>
	<string>298AC028-D72E-4E85-982B-5A38D5B8ABB0</string>
</dict>
</plist>
